services:  
  proj3:
    build: .
    container_name: proj3
    environment:
      - BASE_URL=http://host.docker.internal:12434/engines/llama.cpp/v1/
      - MODEL=ai/llama3.2:latest

      - LLM_ONE_RELIGION=Agnostic
      - LLM_TWO_RELIGION=Atheist
      - TOPIC=Existence of Higher Power
      - TURNS=4
      - SENTENCES=3
    volumes:
      - ./:/app/output
  
  llm:
    provider:
      type: model
      options: 
        model: ai/llama3.2:latest